- name: Upload Screenshots
  uses: actions/upload-artifact@v4
  if: always()
  with:
    name: screenshots
    path: results/screenshots/**/*
    retention-days: 30
    if-no-files-found: warn

- name: Upload Videos
  uses: actions/upload-artifact@v4
  if: always()
  with:
    name: videos
    path: results/videos/**/*
    retention-days: 30
    if-no-files-found: warn
