name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Clean Previous Results
        run: rm -rf results

      - name: Run Tests with Screenshot & Video
        env:
          HEADLESS: "true"
          BASE_URL: ${{ secrets.BASE_URL }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          ACCESS_CODE: ${{ secrets.ACCESS_CODE }}
        run: |
          pytest modules/General/test_Lost_connection.py -m "unit or smoke or regression" --reruns 2 --reruns-delay 3 \
            --base-url "${{ env.BASE_URL }}" \
            --username "${{ env.TEST_USERNAME }}" \
            --password "${{ env.TEST_PASSWORD }}" \
            --slowmo 100

      # --- TAMBAHKAN LANGKAH INI UNTUK MENGINSTAL FFMPEG ---
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Langkah konversi video sekarang akan berhasil
      - name: Convert Videos to MP4
        if: always()
        run: |
          echo "Mencari file video .webm untuk dikonversi..."
          for file in $(find results/videos -name "*.webm"); do
            output_file="${file%.webm}.mp4"
            echo "Mengonversi $file menjadi $output_file"
            ffmpeg -i "$file" -c:v libx264 -preset veryfast -crf 23 -y "$output_file" -loglevel error
            rm "$file"
          done
          echo "Konversi selesai."

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots-${{ github.run_number }}
          path: results/screenshots/**/*
          retention-days: 30
          if-no-files-found: warn

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: videos-${{ github.run_number }}
          path: results/videos/**/*
          retention-days: 30
          if-no-files-found: warn