name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-rerunfailures playwright python-dotenv
          playwright install --with-deps

      - name: Run tests with screenshot & video
        env:
          CI: "true"
        run: |
          pytest -m "unit or smoke or regression" --reruns 2 --reruns-delay 3

      # Upload screenshots as artifact
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-screenshots
          path: results/**/*.png # Jalur yang diperbaiki
          retention-days: 30

      # Upload videos as artifact
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-videos
          path: results/**/*.webm # Jalur yang diperbaiki
          retention-days: 30