name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Clean Previous Results
        run: rm -rf results

      - name: Run tests with screenshot & video
        env:
          HEADLESS: "true"
          BASE_URL: ${{ secrets.BASE_URL }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          
        run: |
          pytest -m "unit or smoke or regression" --reruns 2 --reruns-delay 3 \
            --base-url "${{ env.BASE_URL }}" \
            --username "${{ env.TEST_USERNAME }}" \
            --password "${{ env.TEST_PASSWORD }}"

      # --- PERUBAHAN DITERAPKAN DI SINI ---
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          # Nama artefak dibuat unik dengan nomor eksekusi
          name: screenshots-${{ github.run_number }}
          path: results/screenshots/**/*
          retention-days: 30
          if-no-files-found: warn

      # --- DAN DI SINI ---
      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          # Nama artefak dibuat unik dengan nomor eksekusi
          name: videos-${{ github.run_number }}
          path: results/videos/**/*
          retention-days: 30
          if-no-files-found: warn